### ISSUE TITLE
Update CI to use Solutions & Portable DebugTypes

### ISSUE THREAD

**Issue by carusology** [invio/Invio.Extensions.Reflection#24]
**Background**
As part of our migration to v1.0.4 of the .NET SDK, I [set the `DebugType` to `full`](https://github.com/invio/Invio.Extensions.Reflection/commit/21c39680450053cbc770139b684232f1a38d95d0#diff-a5e78c7a75d5f92bb5991e0d5ed3f8ffR8) and updated the CI scripts to explicitly reference XML-based `*.csproj` files due to the removal of `global.json` and `project.json`. The `DebugType` really should be `portable` for .NET Core when we pack the code (though it needs to be `full` for when we run opencover on it), and we should add a `*.sln` to manage our `*.csproj` files.

**Task**
* [ ] Update the repository to have a `Invio.Extensions.Reflection.sln` solution at the root of the repository that references the source and test projects.
* [ ] Update `Invio.Extensions.Reflection.csproj` such that `<IsPackable>false</IsPackable>` is specified.
* [ ] Restore `set-debug-type.ps1`, but with it updating the `DebugType` via the XML-based `Invio.Extensions.Reflection.csproj` instead of JSON-based `project.json`.
